version: '3'
services:
  my_asterisk_container:
    build:
      context: ./asterisk
      dockerfile: Dockerfile
    environment:
      - SERVER_IP=191.36.8.50
      - SERVER_IP6=2804:1454:1004:101::50
    volumes:
      - ./asterisk/asterisk-conf/ari.conf:/etc/asterisk/ari.conf
      - ./asterisk/asterisk-conf/asterisk.conf:/etc/asterisk/asterisk.conf
      - ./asterisk/asterisk-conf/extensions.conf:/etc/asterisk/extensions.conf
      - ./asterisk/asterisk-conf/host.conf:/etc/asterisk/host.conf
      - ./asterisk/asterisk-conf/manager.conf:/etc/asterisk/manager.conf
      - ./asterisk/asterisk-conf/modules.conf:/etc/asterisk/modules.conf
      - ./asterisk/asterisk-conf/pjsip.conf:/etc/asterisk/pjsip.conf
      - ./asterisk/asterisk-conf/pjsip.conf.d:/etc/asterisk/pjsip.conf.d
      - ./asterisk/asterisk-conf/rtp.conf:/etc/asterisk/rtp.conf
  my_nginx_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro  # Monta o diretório Let's Encrypt com os certificados SSL
    ports:
      - "80:80/tcp"      # HTTP
      - "443:443/tcp"    # HTTPS
      - "5060:5060/udp" # SIP (UDP)
      - "5060:5060/tcp" # SIP (TCP)
      - "5061:5061/tcp" # SIP (TLS)
    depends_on:
      - my_asterisk_container
    command: nginx -g 'daemon off;'
