version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    # Adicionar outras configurações necessárias para o backend, caso necessário

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    # Adicionar outras configurações necessárias para o frontend, caso necessário

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    # Adicionar outras configurações necessárias para o Nginx, caso necessário
