version: '3'
services:
  my_asterisk_container:
    build:
      context: ./asterisk
      dockerfile: Dockerfile
    environment:
      - SERVER_IP=192.168.1.100
    networks:
      my_network:
        ipv4_address: 192.168.1.100
    ports:
      - "8080:8088"  # HTTP
      - "8089:8089"  # WebSocket Secure (WSS)
      - "5060:5060/udp"  # SIP (UDP)

networks:
  my_network:
    ipam:
      config:
        - subnet: 192.168.1.0/24