version: '3'
services:
  sip_uas_1: &sip_uas
    build:
      context: ./SIPp
      dockerfile: Dockerfile
    restart: always
  sip_uas_2:
    <<: *sip_uas
  sip_uas_3:
    <<: *sip_uas
  my_nginx_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5060:5060/udp"
    depends_on:
      - sip_uas_1
      - sip_uas_2
      - sip_uas_3
    command: nginx -g 'daemon off;'
