version: '3'

services:
  opensips:
    build: ./opensips
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
    # Adicionar outras configurações necessárias para o servidor(Opensips), caso necessário

  client:
    build: ./client
    ports:
      - "80:80"
    # Adicionar outras configurações necessárias para o cliente, caso necessário

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - opensips
      - client
    # Adicionar outras configurações necessárias para o Nginx, caso necessário

  sql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: seu_usuario
      POSTGRES_PASSWORD: sua_senha
      POSTGRES_DB: nome_do_banco_de_dados
    ports:
      - "5432:5432"
    volumes:
      - ./dados_postgresql:/var/lib/postgresql/data
      - ./banco_dados/script_cache.py:/app/script_cache.py  # Monte o arquivo Python para a aplicação

  redis:
    image: redis:latest
    ports:
      - "6379:6379"