version: '3'
services:
  my_asterisk_container:
    build:
      context: ./asterisk
      dockerfile: Dockerfile
    environment:
      - SERVER_IP=191.36.8.50
      - SERVER_IP6=2804:1454:1004:101::50
    ports:
      - "5060:5060/udp"  # SIP (UDP)

  my_nginx_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/sites-enabled/default:ro
      - ./nginx/letsencrypt:/etc/letsencrypt:ro  # Monta o diretório Let's Encrypt com os certificados SSL
    ports:
      - "80:80"    # HTTP
      - "443:443"  # HTTPS
    depends_on:
      - my_asterisk_container
    command: nginx -g 'daemon off;'
