version: '3'
services:
  sip_uas_1: &sip_uas
    build:
      context: ./SIPp
      dockerfile: Dockerfile
    restart: always
  sip_uas_2:
    <<: *sip_uas
  sip_uas_3:
    <<: *sip_uas
  my_nginx_proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5060:5060/udp"
    depends_on:
      - sip_uas_1
      - sip_uas_2
      - sip_uas_3
    command: nginx -g 'daemon off;'

  influxdb:
      image: influxdb:1.8
      ports:
        - "8086:8086"
      volumes:
        - influxdb_data:/var/lib/influxdb
      environment:
        INFLUXDB_DB: metrics_sip_call
        INFLUXDB_ADMIN_USER: admin
        INFLUXDB_ADMIN_PASSWORD: tccarthur123
  
  traefik:
    image: traefik:v2.6
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --entrypoints.web.address=:80
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"

  grafana:
    image: grafana/grafana:10.4.3
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.tcc-arthur.sj.ifsc.edu.br`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.entryPoints=web

volumes:
  influxdb_data:
  grafana-data: